name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: Install dependencies
      run: npm install

    - name: Cache Electron builder cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/electron
          ~/.cache/electron-builder
        key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-electron-

    - name: Build the app
      run: npm run build

    - name: Make the app
      run: npm run make

    - name: Publish the app
      run: npm run publish
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/**/*.dmg
          dist/**/*.AppImage
          dist/**/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
